import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";
import { ModeToggle } from "./../components/mode-toggle";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CRUD - NEXT.JS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div>
            <header className="flex items-center justify-between bg-gray-900 text-white p-4">
              <h1 className="text-2xl font-bold">
                <Link href={"/"}>CRUD - NEXT.JS</Link>
              </h1>
              <nav className="flex gap-4 items-center">
                <Link href="/" className="text-gray-300 hover:text-gray-400">
                  Products
                </Link>
                <Link
                  href="/products/add"
                  className="text-gray-300 hover:text-gray-400"
                >
                  Add Product
                </Link>

                {/* <Link
                  href="/sign-in"
                  className="text-gray-300 hover:text-gray-400"
                >
                  Sign In
                </Link> */}

                <ModeToggle />
              </nav>
            </header>
            <main className="container h-[100vh] mx-auto max-w-7xl px-4 sm:px-6">
              {children}
            </main>
            <footer className="bg-gray-800 text-white p-4 text-sm text-center">
              &copy; 2023 CRUD - NEXT.JS. All rights reserved.
            </footer>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
